export default {
  useCreateEntity: "useCreateEntity",
  useFetchEntity: "useFetchEntity",
  useFetchEntityByForeignId: "useFetchEntityByForeignId",
  useFetchEntityByShortId: "useFetchEntityByShortId",
  useFetchManyEntities: "useFetchManyEntities",
  useUpdateEntity: "useUpdateEntity",
  useEntityVotes: "useEntityVotes",
  useUpvoteEntity: "useUpvoteEntity",
  useRemoveEntityUpvote: "useRemoveEntityUpvote",
  useDownvoteEntity: "useDownvoteEntity",
  useRemoveEntityDownvote: "useRemoveEntityDownvote",
  useIncrementEntityViews: "useIncrementEntityViews",
  useDeleteEntity: "useDeleteEntity",
  useInfusedData: "useInfusedData",
  useEntityData: "useEntityData",
  useEntityListData: "useEntityListData",
};
